# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: All Mocha Tests For Windows and Ubuntu

on:
  push:
    branches: [ dev, beta, master ]
  pull_request:
    branches: [ dev, beta, master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, windows-2022, ubuntu-latest, ubuntu-22.04 ]
        node-version: [ 14.x, 16.x, 18.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci

      - if: "!contains(matrix.os, 'windows')"
        run: sudo npm test

      - if: "contains(matrix.os, 'windows')"
        run: npm test
